namespace: hasura

stack:
  defines: process-group
  runnable-list:
    - hasura/hasura-db
    - hasura/hasura
  variables:
    hasura_graphql_console:
      type: string
      value: true
    hasura_graphql_dev_mode:
      type: string
      value: true
    hasura_graphql_enabled_log_types:
      type: string
      value: startup, http-log, webhook-log, websocket-log, query-log
    hasura_graphql_admin_secret:
      type: string
      value: monk
    database_name:
      type: string
      value: monk
    database_password:
      type: string
      value: monk
    database_user:
      type: string
      value: monk
    database_port:
      type: int
      value: 5432
    db_password:
      type: string
      value: monk
    hasura_port:
      type: int
      value: 8080